Added a minimum bound for ResultTypes in order for another package to use v2.0.0
```
ERROR: Unsatisfiable requirements detected for package ResultTypes:
...
├─version range [2.0.0,∞) required by package MyPkg, whose only allowed version is 0.2.0+:
│ └─version 0.2.0+ set by fixed requirement (package is checked out, dirty or pinned)
└─version range [0.1.0,2.0.0) required by package Dispatcher, whose allowed version range is [0.0.0-,∞):
The intersection of the requirements is empty.
```

I'm not sure why the default version range was [0.1.0,2.0.0) though :/